# Generated by Django 4.2.1 on 2023-05-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="diary",
            name="article_img",
            field=models.URLField(),
        ),
    ]
