# Generated by Django 4.2.1 on 2023-05-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_diary_is_private_alter_diary_article_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="article_img",
            field=models.URLField(blank=True, null=True),
        ),
    ]
